site_name: Dokumentation
site_url: https://dietaube007.github.io/Projektarbeit_2026/
repo_url: https://github.com/dietaube007/Projektarbeit_2026
repo_name: dietaube007/Projektarbeit_2026

theme:
  name: material
  language: de
  favicon: assets/petbuddy_logo_2.png
  logo: assets/petbuddy_logo.png
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Dunkelmodus
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Hellmodus
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.html
  - Installation & Quickstart: installation-quickstart.md
  - Technische Dokumentation: technische-dokumentation.md
  - Nutzungshandbuch: nutzungshandbuch.md
  - Technische Strategie: technische-strategie.md